//все острова
https://island-seller.herokuapp.com/islands

###

//By id
https://island-seller.herokuapp.com/islands/1

###

//Saerch
https://island-seller.herokuapp.com/islands/search/Woodgrass

###

//By id region
https://island-seller.herokuapp.com/islands/region/3

###

//By id country
https://island-seller.herokuapp.com/islands/country/2

###

//save
https://island-seller.herokuapp.com/islands/0/save?name=testSAVE&regionId=2&countryId=2&price=100&size=200

###

//update
https://island-seller.herokuapp.com/islands/4/save?name=testUPDATE&regionId=1&countryId=1&price=10&size=20

###

//remove
https://island-seller.herokuapp.com/islands/4/remove
