//все острова
http://localhost:8888/islands

###

//By id
http://localhost:8888/islands/1

###

//Saerch
http://localhost:8888/islands/search/Woodgrass

###

//By id region
http://localhost:8888/islands/region/3

###

//By id country
http://localhost:8888/islands/country/2

###

//save
http://localhost:8888/islands/0/save?name=testSAVE&regionId=2&countryId=2&price=100&size=200

###

//update
http://localhost:8888/islands/4/save?name=testUPDATE&regionId=1&countryId=1&price=10&size=20

###

//remove
http://localhost:8888/islands/4/remove
